apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: Demo API
spec:
  type: service
  owner: yavuzabasiyanik
  lifecycle: experimental
  definition:
    swagger: "2.0"
    info:
      title: "My API"
      version: "1.0.0"
    paths:
      "/users":
        get:
          summary: "Get a list of users"
          parameters:
            - name: "page"
              in: "query"
              description: "The page number to retrieve"
              required: false
              type: "integer"
          responses:
            "200":
              description: "A list of users"