apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: Demo API
spec:
  type: openapi
  owner: yavuzabasiyanik
  lifecycle: experimental
  definition: |
    openapi: "3.0.0"
    info:
      title: "My API"
      version: "1.0.0"
    paths:
      "/users":
        get:
          summary: "Get a list of users"
          responses:
            "200":
              description: "A list of users"
        post