apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: Demo API
spec:
  type: service
  owner: yavuzabasiyanik
  lifecycle: experimental
  definition: "    swagger: \"3.0.4\"\n" +
        "    info:\n" +
        "      title: \"My API\"\n" +
        "      version: \"1.0.0\"\n" +
        "    paths:\n" +
        "      \"/users\":\n" +
        "        get:\n" +
        "          summary: \"Get a list of users\"\n" +
        "          parameters:\n" +
        "            - name: \"page\"\n" +
        "              in: \"query\"\n" +
        "              description: \"The page number to retrieve\"\n" +
        "              required: false\n" +
        "              type: \"integer\"\n" +
        "          responses:\n" +
        "            \"200\":\n" +
        "              description: \"A list of users\""